# Generated by Django 5.1.3 on 2024-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_california_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("opening_hours", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
