# Generated by Django 5.1.2 on 2024-12-01 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_california_app', '0002_spa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message="Le nombre de convives doit être d'au moins 1"), django.core.validators.MaxValueValidator(100, message='Le nombre de convives ne peut pas dépasser 100')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message="La capacité doit être d'au moins 1"), django.core.validators.MaxValueValidator(250, message='La capacité ne peut pas dépasser 250')]),
        ),
    ]
